### ISSUE TITLE
Add git-hg mirror for JDK 9 and JDK 10

### ISSUE THREAD

**Issue by sunnychanwork** [AdoptOpenJDK/openjdk-releases#8]
I know we are probably not looking to build the OpenJDK on JDK 9 and 10 yet but would it be possible to setup github mirror for JDK 9 and JDK 10 without building it, using the same hg-git script use for JDK 8?

**Comment by karianna** [comment]
Duplicate issues in the openjdk-build repo https://github.com/AdoptOpenJDK/openjdk-build/issues/8 and https://github.com/AdoptOpenJDK/openjdk-build/issues/9

In short yes we'll be doing this but after we have a known, good, tested stable 8 first.
